/**
 * Upscale Vintage — canonical SEO (overrides CMS for meta tags & social).
 * CMS remains for on-page editable copy; titles/descriptions/OG come from here.
 */
import type { Metadata } from 'next';
import {
  APP_TITLE,
  BRAND_NAME,
  TAGLINE,
  CONTACT_ADDRESS,
  CONTACT_PHONE_DISPLAY,
  INSTAGRAM_HANDLE,
  INSTAGRAM_URL,
  WHATSAPP_LINK,
} from '@/lib/brand';

export const SITE_URL =
  process.env.NEXT_PUBLIC_APP_URL?.replace(/\/$/, '') || 'https://upscalevintage.com';

/** Social & OG image paths (generated by scripts/generate-seo-assets.mjs) */
export const SEO_ASSETS = {
  ogImage: '/og-image.png',
  ogImageSquare: '/og-image-square.png',
  twitterCard: '/twitter-card.png',
  logo: '/logo.png',
  faviconDir: '/favicon',
  faviconIco: '/favicon/favicon.ico',
  favicon16: '/favicon/favicon-16x16.png',
  favicon32: '/favicon/favicon-32x32.png',
  appleTouchIcon: '/favicon/apple-touch-icon.png',
  icon192: '/favicon/android-chrome-192x192.png',
  icon512: '/favicon/android-chrome-512x512.png',
} as const;

export const DEFAULT_TITLE =
  'Upscale Vintage | Trending Lifestyle & Import Plug in Ghana';

export const DEFAULT_DESCRIPTION =
  'Upscale Vintage: your trending lifestyle destination and import plug in Ghana. Shop fashion, home appliances, bags, accessories, and curated imports online.';

export const DEFAULT_KEYWORDS = [
  BRAND_NAME,
  'Upscale Vintage Ghana',
  'fashion shop Accra',
  'imported fashion Ghana',
  'designer bags Ghana',
  'lifestyle imports Accra',
  'trending lifestyle Ghana',
  'import plug Ghana',
  'home appliances online Ghana',
  'trending fashion online',
  'accessories online Ghana',
  'social commerce fashion',
  'buy fashion online Ghana',
  'imported lifestyle products',
  'vintage inspired fashion',
  'Hatso Agbogba fashion',
];

export type PageSeoKey =
  | 'home'
  | 'shop'
  | 'categories'
  | 'about'
  | 'contact'
  | 'cart'
  | 'wishlist'
  | 'faqs'
  | 'shipping'
  | 'returns'
  | 'privacy'
  | 'terms'
  | 'blog'
  | 'orderTracking';

const PAGE_SEO: Record<
  PageSeoKey,
  { title: string; description: string; keywords?: string[]; path: string; noindex?: boolean }
> = {
  home: {
    title: DEFAULT_TITLE,
    description: DEFAULT_DESCRIPTION,
    path: '/',
  },
  shop: {
    title: 'Shop Trending Lifestyle & Imports',
    description:
      'Browse fashion, home appliances, bags, accessories, beauty, and import-ready lifestyle products. New arrivals and featured picks updated regularly.',
    keywords: ['shop fashion Ghana', 'home appliances Ghana', 'import plug Accra', 'lifestyle shop Accra'],
    path: '/shop',
  },
  categories: {
    title: 'Shop by Category',
    description:
      'Explore Upscale Vintage categories: fashion, home appliances, bags, accessories, lifestyle finds, imports, and more. Curated for every shopper.',
    keywords: ['fashion categories', 'home appliances category', 'shop by category Ghana'],
    path: '/categories',
  },
  about: {
    title: 'About Us | Our Story & Mission',
    description:
      'Upscale Vintage is your trending lifestyle destination and import plug in Accra: fashion, appliances, and curated arrivals for all.',
    keywords: ['about Upscale Vintage', 'trending lifestyle brand Ghana', 'import plug Ghana'],
    path: '/about',
  },
  contact: {
    title: 'Contact Us | Orders, WhatsApp & Visit',
    description:
      'Reach Upscale Vintage by phone, WhatsApp, or in person at Hatso Agbogba Salasi Junction, Accra. Questions about orders, reservations, and imports welcome.',
    keywords: ['contact Upscale Vintage', 'fashion store Accra contact'],
    path: '/contact',
  },
  cart: {
    title: 'Your Cart',
    description: 'Review items in your cart and checkout securely with Upscale Vintage.',
    path: '/cart',
    noindex: true,
  },
  wishlist: {
    title: 'Wishlist',
    description: 'Save your favorite fashion and lifestyle finds from Upscale Vintage.',
    path: '/wishlist',
    noindex: true,
  },
  faqs: {
    title: 'FAQs | Orders, Delivery & Payments',
    description:
      'Answers about ordering, delivery in Ghana, Mobile Money payments, returns, and shopping imported fashion at Upscale Vintage.',
    path: '/faqs',
  },
  shipping: {
    title: 'Shipping & Delivery',
    description:
      'Delivery times and shipping information for Upscale Vintage orders within Ghana.',
    path: '/shipping',
  },
  returns: {
    title: 'Returns & Refunds | Refund Policy',
    description:
      'Upscale Vintage refund policy: eligible refunds, 24 hour exchange window, and how to start a return in Ghana.',
    path: '/returns',
  },
  privacy: {
    title: 'Privacy Policy',
    description: 'How Upscale Vintage collects, uses, and protects your personal information.',
    path: '/privacy',
  },
  terms: {
    title: 'Terms of Service',
    description: 'Terms and conditions for shopping with Upscale Vintage.',
    path: '/terms',
  },
  blog: {
    title: 'Style Journal & Updates',
    description: 'Fashion tips, lifestyle inspiration, and news from Upscale Vintage.',
    path: '/blog',
  },
  orderTracking: {
    title: 'Track Your Order',
    description: 'Track your Upscale Vintage order status with your order number and email.',
    path: '/order-tracking',
    noindex: true,
  },
};

function absoluteUrl(path: string): string {
  return path.startsWith('http') ? path : `${SITE_URL}${path.startsWith('/') ? path : `/${path}`}`;
}

function absoluteImage(path: string): string {
  return absoluteUrl(path);
}

export function buildPageMetadata(
  key: PageSeoKey,
  overrides?: Partial<{
    title: string;
    description: string;
    keywords: string[];
    path: string;
    ogImage: string;
    ogType: 'website' | 'article';
    noindex: boolean;
  }>
): Metadata {
  const page = PAGE_SEO[key];
  const title = overrides?.title ?? page.title;
  const description = overrides?.description ?? page.description;
  const path = overrides?.path ?? page.path;
  const keywords = [...DEFAULT_KEYWORDS, ...(overrides?.keywords ?? page.keywords ?? [])];
  const noindex = overrides?.noindex ?? page.noindex ?? false;
  const ogImage = overrides?.ogImage ?? SEO_ASSETS.ogImage;
  const canonical = absoluteUrl(path);

  const fullTitle = title.includes(APP_TITLE) ? title : `${title} | ${APP_TITLE}`;

  return {
    title: fullTitle,
    description,
    keywords,
    alternates: { canonical },
    robots: noindex
      ? { index: false, follow: false }
      : {
          index: true,
          follow: true,
          googleBot: {
            index: true,
            follow: true,
            'max-image-preview': 'large',
            'max-snippet': -1,
            'max-video-preview': -1,
          },
        },
    openGraph: {
      type: overrides?.ogType ?? 'website',
      locale: 'en_GH',
      url: canonical,
      siteName: APP_TITLE,
      title: fullTitle,
      description,
      images: [
        {
          url: absoluteImage(ogImage),
          width: 1200,
          height: 630,
          alt: `${BRAND_NAME}: ${TAGLINE}`,
          type: 'image/png',
        },
        {
          url: absoluteImage(SEO_ASSETS.ogImageSquare),
          width: 1200,
          height: 1200,
          alt: BRAND_NAME,
          type: 'image/png',
        },
      ],
    },
    twitter: {
      card: 'summary_large_image',
      title: fullTitle,
      description,
      images: [absoluteImage(SEO_ASSETS.twitterCard)],
      creator: INSTAGRAM_HANDLE,
      site: INSTAGRAM_HANDLE,
    },
  };
}

/** Root layout metadata — favicons, defaults, verification hooks */
export function buildRootMetadata(): Metadata {
  const googleVerification = process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION;

  return {
    metadataBase: new URL(SITE_URL),
    title: {
      default: DEFAULT_TITLE,
      template: `%s | ${APP_TITLE}`,
    },
    description: DEFAULT_DESCRIPTION,
    keywords: DEFAULT_KEYWORDS,
    authors: [{ name: BRAND_NAME, url: SITE_URL }],
    creator: BRAND_NAME,
    publisher: BRAND_NAME,
    applicationName: APP_TITLE,
    category: 'shopping',
    referrer: 'origin-when-cross-origin',
    formatDetection: { telephone: true, email: false, address: false },
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
        'max-image-preview': 'large',
        'max-snippet': -1,
        'max-video-preview': -1,
      },
    },
    icons: {
      icon: [
        { url: SEO_ASSETS.faviconIco, sizes: 'any' },
        { url: SEO_ASSETS.favicon16, sizes: '16x16', type: 'image/png' },
        { url: SEO_ASSETS.favicon32, sizes: '32x32', type: 'image/png' },
        { url: SEO_ASSETS.icon192, sizes: '192x192', type: 'image/png' },
        { url: SEO_ASSETS.icon512, sizes: '512x512', type: 'image/png' },
      ],
      shortcut: SEO_ASSETS.faviconIco,
      apple: [{ url: SEO_ASSETS.appleTouchIcon, sizes: '180x180', type: 'image/png' }],
    },
    manifest: '/manifest.json',
    appleWebApp: {
      capable: true,
      statusBarStyle: 'default',
      title: 'Upscale',
    },
    verification: googleVerification ? { google: googleVerification } : undefined,
    openGraph: {
      type: 'website',
      locale: 'en_GH',
      url: SITE_URL,
      siteName: APP_TITLE,
      title: DEFAULT_TITLE,
      description: DEFAULT_DESCRIPTION,
      images: [
        {
          url: absoluteImage(SEO_ASSETS.ogImage),
          width: 1200,
          height: 630,
          alt: BRAND_NAME,
        },
      ],
    },
    twitter: {
      card: 'summary_large_image',
      title: DEFAULT_TITLE,
      description: DEFAULT_DESCRIPTION,
      images: [absoluteImage(SEO_ASSETS.twitterCard)],
      creator: INSTAGRAM_HANDLE,
    },
    alternates: { canonical: SITE_URL },
  };
}

export function organizationJsonLd() {
  return {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    '@id': `${SITE_URL}/#organization`,
    name: APP_TITLE,
    alternateName: BRAND_NAME,
    url: SITE_URL,
    logo: absoluteImage(SEO_ASSETS.logo),
    image: absoluteImage(SEO_ASSETS.ogImage),
    description: DEFAULT_DESCRIPTION,
    address: {
      '@type': 'PostalAddress',
      streetAddress: CONTACT_ADDRESS,
      addressLocality: 'Accra',
      addressRegion: 'Greater Accra',
      addressCountry: 'GH',
    },
    contactPoint: [
      {
        '@type': 'ContactPoint',
        telephone: CONTACT_PHONE_DISPLAY,
        contactType: 'customer service',
        areaServed: 'GH',
        availableLanguage: ['English'],
      },
    ],
    sameAs: [INSTAGRAM_URL, WHATSAPP_LINK],
  };
}

export function websiteJsonLd() {
  return {
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    '@id': `${SITE_URL}/#website`,
    name: APP_TITLE,
    url: SITE_URL,
    description: DEFAULT_DESCRIPTION,
    publisher: { '@id': `${SITE_URL}/#organization` },
    potentialAction: {
      '@type': 'SearchAction',
      target: {
        '@type': 'EntryPoint',
        urlTemplate: `${SITE_URL}/shop?search={search_term_string}`,
      },
      'query-input': 'required name=search_term_string',
    },
  };
}

export function localBusinessJsonLd() {
  return {
    '@context': 'https://schema.org',
    '@type': 'ClothingStore',
    '@id': `${SITE_URL}/#store`,
    name: APP_TITLE,
    image: absoluteImage(SEO_ASSETS.ogImage),
    url: SITE_URL,
    telephone: CONTACT_PHONE_DISPLAY,
    address: {
      '@type': 'PostalAddress',
      streetAddress: CONTACT_ADDRESS,
      addressLocality: 'Accra',
      addressCountry: 'GH',
    },
    priceRange: '$$',
    currenciesAccepted: 'GHS',
    paymentAccepted: 'Mobile Money, Bank Transfer, Card',
    openingHoursSpecification: {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
      opens: '09:00',
      closes: '18:00',
    },
    sameAs: [INSTAGRAM_URL],
  };
}

export function productJsonLd(product: {
  name: string;
  description: string;
  image: string;
  slug: string;
  price: number;
  currency?: string;
  sku?: string;
  inStock: boolean;
  brand?: string;
}) {
  return {
    '@context': 'https://schema.org',
    '@type': 'Product',
    name: product.name,
    description: product.description,
    image: product.image.startsWith('http') ? product.image : absoluteUrl(product.image),
    sku: product.sku || product.slug,
    brand: { '@type': 'Brand', name: product.brand || BRAND_NAME },
    offers: {
      '@type': 'Offer',
      url: `${SITE_URL}/product/${product.slug}`,
      priceCurrency: product.currency || 'GHS',
      price: product.price,
      availability: product.inStock
        ? 'https://schema.org/InStock'
        : 'https://schema.org/OutOfStock',
      seller: { '@id': `${SITE_URL}/#organization` },
    },
  };
}

export function breadcrumbJsonLd(items: { name: string; path: string }[]) {
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: items.map((item, index) => ({
      '@type': 'ListItem',
      position: index + 1,
      name: item.name,
      item: absoluteUrl(item.path),
    })),
  };
}
